[images]
  remote_images = ["https://my-images.com/.*", "https://animals.more-images.com/[bcr]at/.*"]
  remote_images = [
    'mars.nasa.gov',
    'mars.jpl.nasa.gov',
    'i.annihil.us',
    'https://mars.nasa.gov',
    'https://mars.jpl.nasa.gov',
    'https://i.annihil.us',
    'https://mars.nasa.gov/.*',
    'https://mars.jpl.nasa.gov/.*',
    'https://i.annihil.us/.*'
  ]
